### PR TITLE
Update Steam Audio to version 4.5.3

### PR DESCRIPTION
**Pull request by stanriders**
Boolean being `U4` didn't really work on my side while default `U1` or even `Bool` worked just fine so I've decided to include that in the diff. Other than that it's just a straight up phonon/cppcodegen update. 

Newest versions of `CppAst.CodeGen` use net8 with `nint` pointers which is quite a breaking change (would require the lib to target net8 instead of netstandard2.0) so it's not included here

### CODE REVIEW

**Comment by Mirsario** [comment]
Thank you, this is good. However, this is a pretty old & unkempt repo that contains a few decisions that I nowadays consider to be mistakes.

I have now pushed a compact history rewrite on `dev` that:
- Gets rid of natives and headers distributed in the tree, in favor of manual installation of them. Otherwise, non-shallow clones of the repo will quickly grow to gigabytes, as Phonon's binaries are very large. A submodule with reliable C++ building may be better in the future, now that we've been blessed with the opensourcing.
- Splits natives out of the main NuGet package into `SteamAudio.NET.Natives`. People could already avoid 'consuming' natives out of packages, but I believe that doesn't shrink the ~130MB download?
- Prettifies some files.

..& will now force-push a rebase here. Backup your local copies if necessary.

**Comment by Mirsario** [comment]
Cool, thanks to GitHub for closing this. I should've pushed first & changed base after. I've pushed the rebase on my remote as `pr/update-phonon`, please recreate the PR from a copy of it.

**Comment by stanriders** [comment]
image
Unfortunaly I can't haha. I also forgot to update `Shared.targets` and now can't do it since this isn't my branch now

**Comment by Mirsario** [comment]
That's why I said 'from a copy of it', take my edit of your branch to your fork/remote (or just run your own rebase, a matter of removing some files). My apologies for these shenanigans.
The Shared.targets file was added in a new commit, you didn't forget it.

**Pull request closed without merging**
